PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX roh: <http://purl.org/roh>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?startTime ?endTime
WHERE {
  ?superviseeRole a roh:SuperviseeRole ;
                  obo:RO_0000052 <http://myuri.net/memaldi> ;
                  vivo:relatedBy ?supervisingRelationship .
  ?supervisingRelationship a roh:PhDSupervisingRelationship ;
                            vivo:dateTimeInterval ?dateTimeInterval .
  ?dateTimeInterval vivo:start ?start ;
                    vivo:end ?end .
  ?start vivo:dateTime ?startTime .
  ?end vivo:dateTime ?endTime .
}