PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX roh: <http://purl.org/roh>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT ?supervisors
WHERE {
  ?superviseeRole a roh:SuperviseeRole ;
     obo:RO_0000052 <http://myuri.net/john> ;
   vivo:relatedBy ?supervisingRelationship .
  ?supervisingRelationship a roh:PhDSupervisingRelationship ;
    vivo:relates ?supervisorRole .
  ?supervisorRole a roh:SupervisorRole ;
  obo:RO_0000052 ?supervisors .
}

