PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX roh: <http://purl.org/roh#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?editor
WHERE {
	<http://myurl/book> bibo:editorList ?editorList .
  	?editorList ?p	?editor .
  	?editor a	foaf:Person .
}