PREFIX foaf: <http://purl.org/roh/mirror/foaf#>
PREFIX unesco: <http://purl.org/roh/unesco-individuals#>
PREFIX ro: <http://purl.org/obo/owl/ro#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?researcher ?center ?positionClass
WHERE {
  ?researcher        roh:hasKnowledgeArea unesco:C00261 ;
                                  roh:hasPosition ?position .
  ?position vivo:relates ?center ;
                          a        ?positionClass .
  ?center a roh:ResearchGroup .
}